image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar -P:profile=test ./artifacts/app-ibank.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info